(() => {
'use strict';
const STORAGE_KEY='derby-character-cash-v1',DB_NAME='derby-character-cash-avatars',DB_STORE='avatars',BACKUP_VERSION=1,MAX_IMAGE_BYTES=5*1024*1024;
const PILLARS=[['Trustworthiness','trust','🛡','Be honest. Keep your word.'],['Respect','respect','♟','Treat people well.'],['Responsibility','responsibility','⛰','Do your best. Own it.'],['Fairness','fairness','⚖','Be fair. Include others.'],['Caring','caring','♥','Be kind. Help others.'],['Citizenship','citizenship','◎','Make our school better.']];
const DEFAULT_REWARDS=[['Choose Your Seat Pass','Pick your seat for one class.',12,'▣'],['Music Request Pass','Choose a clean work-time song.',15,'♫'],['Sit With a Friend Pass','Choose a classroom partner.',18,'♟'],['Classroom VIP Pass','Be the teacher helper for a class.',20,'★'],['Activity Pass','Choose a five-minute class activity.',22,'⚡'],['Morning Announcement Guest','Share a positive message on announcements.',28,'◉'],['Teacher Choice Pass','A special classroom privilege.',25,'✦'],['Class Experience Pass','Help choose a future class experience.',30,'☀']];
const $=s=>document.querySelector(s),screen=$('#screen'),dialog=$('#dialog'),dialogBody=$('#dialogBody'),avatarInput=$('#avatarFile'),restoreInput=$('#restoreFile'),csvInput=$('#csvFile');
let view='class',query='',selected=new Set(),flash=new Set(),lastAward=null,detailId=null,rewardIndex=null,pendingAvatarId=null,avatarUrls=new Set(),awardTimer=null,state=loadState();
function uid(prefix='id'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function now(){return new Date().toISOString()}
function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function activeClasses(){return state.classes.filter(c=>!c.archived)}
function currentClass(){return state.classes.find(c=>c.id===state.currentClassId&&!c.archived)||activeClasses()[0]||null}
function classStudents(classId=currentClass()?.id){return state.students.filter(s=>s.classId===classId)}
function studentById(id){return state.students.find(s=>s.id===id)}
function pillarIcon(name){return PILLARS.find(p=>p[0]===name)?.[2]||'+'}
function formatNames(ids){const names=ids.map(id=>studentById(id)?.name).filter(Boolean);return names.length<2?(names[0]||'student'):names.length===2?names.join(' and '):names.slice(0,-1).join(', ')+' and '+names.at(-1)}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function toast(message,error=false){document.querySelector('.toast')?.remove();const n=document.createElement('div');n.className='toast'+(error?' error':'');n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),4200)}
function storageError(message){const b=$('#storageBanner');b.textContent=message;b.classList.add('error')}
function seedState(){
 const classNames=['Period 1 — English','Period 2 — Science','Period 3 — Music','Period 5 — Math'],classes=classNames.map(name=>({id:uid('class'),name,archived:false}));
 const names=[['Aiden K.','Lena V.','Owen F.','Priya N.','Diego S.','Nora J.','Micah B.','Elise T.','Rory P.','Samira H.','Theo C.','June A.','Keira L.','Bruno P.','Megan C.','Isaac W.','Talia R.','Emmett G.','Luca H.','Piper B.','Seth N.','Vera D.','Miles A.','Ayla J.'],['Harper B.','Milo G.','Iris K.','Dante R.','Wren S.','Leo M.','Amaya F.','Kai D.','Tessa P.','Roman J.','Ari V.','Quinn L.','Nova C.','Gavin E.','Sage T.','Dexter H.','Malia J.','Cruz B.','Remy P.','Sienna W.','Omar N.','Elsie R.','Beau K.','Nina G.'],['Maya R.','Jamal T.','Sofia C.','Ethan B.','Ava K.','Lily S.','Noah D.','Caleb M.','Zoe P.','Lucas G.','Chloe W.','Mason L.','Aria H.','Tyler J.','Elena F.','Cole N.','Reese V.','Jaden P.','Olivia B.','Asher C.','Kiara M.','Logan T.','Bella A.','Wyatt S.'],['Julian E.','Isla M.','Bennett R.','Camila D.','Nico A.','Ruby F.','Elliot V.','Mira S.','Parker C.','Olive J.','Finn T.','Anika B.','Soren K.','Layla P.','Maddox G.','Cora W.','Jace H.','Vivian D.','Axel N.','Raina L.','Gabe F.','Mina R.','Dylan B.','Nell S.']];
 const balances=[[22,38,17,29,31,26,19,34,28,23,36,21,27,18,33,24,30,20,37,25,29,32,23,35],[24,32,19,26,35,22,37,28,20,31,25,39,23,34,21,29,36,18,27,33,24,30,22,38],[42,28,35,19,26,47,31,18,33,21,29,40,27,24,36,22,30,25,38,20,34,28,32,23],[30,24,39,22,27,34,18,29,25,36,21,32,26,37,23,31,19,35,28,24,33,20,30,27]];
 const students=[];classes.forEach((c,ci)=>names[ci].forEach((name,i)=>students.push({id:uid('student'),classId:c.id,name,instrument:ci===2?['Flute','Clarinet','Alto saxophone','Trumpet','Trombone','Percussion'][i%6]:'',balance:balances[ci][i],createdAt:now()})));
 const id=n=>students.find(s=>s.name===n)?.id,events=[['Responsibility',['Maya R.','Jamal T.','Sofia C.']],['Respect',['Caleb M.']],['Caring',['Zoe P.']],['Trustworthiness',['Noah D.']]].map((e,i)=>({id:uid('event'),pillar:e[0],studentIds:e[1].map(id),classId:classes[2].id,createdAt:new Date(Date.now()-i*900000).toISOString()}));
 return {version:1,classes,students,events,currentClassId:classes[2].id,settings:{animation:true},rewards:DEFAULT_REWARDS.map(r=>({name:r[0],description:r[1],price:r[2],icon:r[3]}))};
}
function validateState(d){return d&&d.version===1&&Array.isArray(d.classes)&&Array.isArray(d.students)&&Array.isArray(d.events)&&d.settings&&d.students.every(s=>typeof s.id==='string'&&typeof s.classId==='string'&&typeof s.name==='string'&&Number.isFinite(s.balance))}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(validateState(parsed))return parsed}}catch(e){setTimeout(()=>storageError('Stored classroom data could not be read. Restore a backup if needed.'),0)}const fresh=seedState();try{localStorage.setItem(STORAGE_KEY,JSON.stringify(fresh))}catch(e){}return fresh}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true}catch(e){storageError('Changes could not be saved. Export a backup and check browser storage.');toast('Save failed. The latest change may not survive a refresh.',true);return false}}
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(DB_STORE))req.result.createObjectStore(DB_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function avatarPut(id,blob){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(blob,id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function avatarGet(id){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE).objectStore(DB_STORE).get(id);req.onsuccess=()=>{db.close();resolve(req.result||null)};req.onerror=()=>{db.close();reject(req.error)}})}
async function avatarDelete(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function avatarClear(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).clear();tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function avatarAll(){const db=await openDb();return new Promise((resolve,reject)=>{const store=db.transaction(DB_STORE).objectStore(DB_STORE),keys=store.getAllKeys(),values=store.getAll();let done=0,k,v;const finish=()=>{if(++done===2){db.close();resolve(k.map((id,i)=>[id,v[i]]))}};keys.onsuccess=()=>{k=keys.result;finish()};values.onsuccess=()=>{v=values.result;finish()};keys.onerror=values.onerror=()=>{db.close();reject(keys.error||values.error)}})}
async function avatarReplaceAll(entries){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite'),store=tx.objectStore(DB_STORE);store.clear();for(const [id,blob] of entries)store.put(blob,id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error||new Error('Avatar restore was cancelled.'))}})}
function revokeAvatarUrls(){avatarUrls.forEach(URL.revokeObjectURL);avatarUrls.clear()}
async function hydrateAvatars(){revokeAvatarUrls();for(const img of document.querySelectorAll('[data-avatar-id]'))try{const blob=await avatarGet(img.dataset.avatarId);if(blob){const u=URL.createObjectURL(blob);avatarUrls.add(u);img.src=u;img.hidden=false;img.nextElementSibling?.setAttribute('hidden','')}}catch(e){storageError('Avatar storage is unavailable. Names and balances remain accessible.')}}
function avatarMarkup(s,cls='avatar'){return `<img class="${cls}" data-avatar-id="${esc(s.id)}" alt="${esc(s.name)} avatar" hidden><span class="avatar-placeholder" aria-hidden="true">${esc(s.name.trim().charAt(0).toUpperCase()||'?')}</span>`}
function nav(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function render(){nav();revokeAvatarUrls();if(view==='class')renderClass();else if(view==='rewards')renderRewards();else if(view==='reports')renderReports();else if(view==='students')renderStudents();else if(view==='setup')renderSetup();else renderSettings();hydrateAvatars()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;query='';detailId=null;selected.clear();flash.clear();clearTimeout(awardTimer);render()});
function recentRows(limit=4){return state.events.filter(e=>!e.type).slice(0,limit).map(e=>`<div class="row"><b>${pillarIcon(e.pillar)}</b><b>+1 ${esc(e.pillar)}</b><span>${esc(formatNames(e.studentIds))}</span><span>${new Date(e.createdAt).toLocaleString()}</span></div>`).join('')||'<p class="helper">No recognition recorded yet.</p>'}
function renderClass(){const c=currentClass();if(!c){screen.innerHTML='<div class="empty"><h2>Create your first class</h2><button id="goSetup" class="primary">Open Class Setup</button></div>';$('#goSetup').onclick=()=>{view='setup';render()};return}state.currentClassId=c.id;const roster=classStudents(c.id),shown=roster.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())),all=shown.length&&shown.every(s=>selected.has(s.id)),events=state.events.filter(e=>e.classId===c.id&&!e.type);screen.innerHTML=`<div class="controls"><select id="classSelect" class="class-select" aria-label="Class period">${activeClasses().map(x=>`<option value="${esc(x.id)}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><input id="classSearch" class="search" aria-label="Search class roster" placeholder="⌕  Search students..." value="${esc(query)}"><span class="count">${roster.length} Students</span><button id="selectAll" class="select-all">${all?'Clear All':'Select All'}</button></div><div class="grid">${shown.map(s=>`<button class="student ${selected.has(s.id)?'selected ':''}${flash.has(s.id)?'awarded':''}" aria-pressed="${selected.has(s.id)}" data-student="${esc(s.id)}"><span class="check">✓</span>${avatarMarkup(s)}<div class="name">${esc(s.name)}</div><div class="instrument">${esc(s.instrument||'')}</div><div class="balance">$${s.balance}</div></button>`).join('')}</div><div class="pillars">${PILLARS.map(p=>`<button class="pillar ${p[1]}" data-pillar="${p[0]}"><i>${p[2]}</i><strong>${p[0]}</strong><small>${p[3]}</small></button>`).join('')}</div><div class="notice ${lastAward?'show':''}"><b class="ok">✓</b><span>${lastAward?`<b>Recognized for ${esc(lastAward.pillar)}.</b> +1 awarded to ${esc(formatNames(lastAward.studentIds))}.`:''}</span><button id="undo" class="undo">Undo</button></div><div class="panels"><div class="panel"><h2>◷ &nbsp; Recent Activity</h2>${recentRows()}</div><div class="panel"><h2>▥ &nbsp; Session Totals</h2><div class="stats"><div class="stat"><b>${events.reduce((n,e)=>n+e.studentIds.length,0)}</b><span>Recognitions</span></div><div class="stat"><b>${new Set(events.flatMap(e=>e.studentIds)).size}</b><span>Students</span></div><div class="stat"><b>${new Set(events.map(e=>e.pillar)).size}</b><span>Traits</span></div></div><div class="quote">“Small actions make a big difference.”</div></div><div class="panel reminders"><h2>▣ &nbsp; Quick Reminders</h2><ul><li>Notice the behavior.</li><li>Name the character trait.</li><li>A quick click makes a big impact.</li></ul></div></div>`;
 $('#classSelect').onchange=e=>{state.currentClassId=e.target.value;query='';selected.clear();saveState();render()};$('#classSearch').oninput=e=>{query=e.target.value;render();$('#classSearch').focus();$('#classSearch').setSelectionRange(query.length,query.length)};$('#selectAll').onclick=()=>{shown.forEach(s=>all?selected.delete(s.id):selected.add(s.id));render()};document.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>{selected.has(b.dataset.student)?selected.delete(b.dataset.student):selected.add(b.dataset.student);render()});document.querySelectorAll('[data-pillar]').forEach(b=>b.onclick=()=>award(b.dataset.pillar));$('#undo').onclick=undoAward;
}
function award(pillar){if(!selected.size)return toast('Select at least one student first.',true);const ids=[...selected],previous=ids.map(id=>[id,studentById(id).balance]);ids.forEach(id=>studentById(id).balance++);const event={id:uid('event'),pillar,studentIds:ids,classId:currentClass().id,createdAt:now()};state.events.unshift(event);lastAward={eventId:event.id,studentIds:ids,pillar,previous};if(!saveState()){previous.forEach(([id,b])=>studentById(id).balance=b);state.events.shift();return}flash=state.settings.animation?new Set(ids):new Set();selected.clear();render();clearTimeout(awardTimer);awardTimer=setTimeout(()=>{flash.clear();document.querySelectorAll('.awarded').forEach(x=>x.classList.remove('awarded'))},720)}
function undoAward(){if(!lastAward)return;lastAward.previous.forEach(([id,b])=>{const s=studentById(id);if(s)s.balance=b});state.events=state.events.filter(e=>e.id!==lastAward.eventId);lastAward=null;saveState();render()}
function renderRewards(){const people=state.students.filter(s=>!state.classes.find(c=>c.id===s.classId)?.archived);screen.innerHTML=`<div class="head"><div><h2>Rewards</h2><p>Simple privileges and experiences.</p></div></div><div class="rewards">${state.rewards.map((r,i)=>`<button class="reward ${rewardIndex===i?'selected-reward':''}" data-reward="${i}"><b style="font-size:31px">${esc(r.icon)}</b><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><span class="price">$${r.price}</span></button>`).join('')}</div><div class="redeem"><b>Redeem a privilege</b><select id="rewardStudent">${people.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — $${s.balance}</option>`).join('')}</select><span>${rewardIndex===null?'Choose a privilege above.':`${esc(state.rewards[rewardIndex].name)} — $${state.rewards[rewardIndex].price}`}</span><button id="redeem" class="primary" ${rewardIndex===null||!people.length?'disabled':''}>Confirm redemption</button></div>`;document.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>{rewardIndex=+b.dataset.reward;render()});$('#redeem').onclick=()=>{const s=studentById($('#rewardStudent').value),r=state.rewards[rewardIndex];if(!s||!r)return;if(s.balance<r.price)return toast(`${s.name} needs more Character Cash.`,true);if(!confirm(`Redeem ${r.name} for ${s.name}?`))return;s.balance-=r.price;state.events.unshift({id:uid('event'),type:'redemption',reward:r.name,amount:r.price,studentIds:[s.id],classId:s.classId,createdAt:now()});saveState();rewardIndex=null;toast(`Redeemed for ${s.name}.`);render()}}
function renderReports(){const rec=state.events.filter(e=>!e.type),totals={};rec.forEach(e=>totals[e.pillar]=(totals[e.pillar]||0)+e.studentIds.length);const max=Math.max(1,...Object.values(totals));screen.innerHTML=`<div class="head"><div><h2>Reports</h2><p>A clear, positive snapshot of character recognition.</p></div></div><div class="reports"><div class="panel"><h2>Recognition by Character Pillar</h2>${PILLARS.map(p=>{const n=totals[p[0]]||0;return `<div class="barrow"><span>${p[0]}</span><div class="bar"><i class="${p[1]}" style="width:${100*n/max}%"></i></div><b>${n}</b></div>`}).join('')}</div><div class="panel"><h2>Activity summary</h2><div class="summary"><div><b>${rec.reduce((n,e)=>n+e.studentIds.length,0)}</b>recognitions</div><div><b>${new Set(rec.flatMap(e=>e.studentIds)).size}</b>students reached</div><div><b>${new Set(rec.map(e=>e.pillar)).size}</b>traits named</div><div><b>${activeClasses().length}</b>active classes</div></div></div></div><div class="panel" style="margin-top:14px"><h2>Recent recognition</h2>${recentRows(8)}</div>`}
function renderStudents(){if(detailId)return renderProfile();const list=state.students.filter(s=>!state.classes.find(c=>c.id===s.classId)?.archived&&s.name.toLowerCase().includes(query.toLowerCase()));screen.innerHTML=`<div class="head"><div><h2>Students</h2><p>Positive character-recognition profiles.</p></div><input id="studentSearch" class="search" style="margin:0" placeholder="⌕  Search students..." value="${esc(query)}"></div><div class="list">${list.map(s=>`<button data-detail="${esc(s.id)}"><b>${esc(s.name)}</b><span>${esc(state.classes.find(c=>c.id===s.classId)?.name||'')} · $${s.balance}${s.instrument?' · '+esc(s.instrument):''}</span></button>`).join('')}</div>`;$('#studentSearch').oninput=e=>{query=e.target.value;render();$('#studentSearch').focus();$('#studentSearch').setSelectionRange(query.length,query.length)};document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{detailId=b.dataset.detail;render()})}
function renderProfile(){const s=studentById(detailId);if(!s){detailId=null;return renderStudents()}const history=state.events.filter(e=>e.studentIds.includes(s.id));screen.innerHTML=`<button id="backStudents" class="secondary">← Student roster</button><div class="detail" style="margin-top:15px"><div class="card"><div style="display:flex;gap:14px;align-items:center">${avatarMarkup(s,'roster-avatar')}<div><h2>${esc(s.name)}</h2><p>${esc(state.classes.find(c=>c.id===s.classId)?.name||'')}</p></div></div><div class="big">$${s.balance}</div><b>Character Cash balance</b><p style="margin-top:12px">${esc(s.instrument||'No instrument listed')}</p></div><div class="panel"><h2>Recognized for</h2><div class="mini">${PILLARS.map(p=>`<div class="${p[1]}"><b>${history.filter(e=>e.pillar===p[0]).length}</b>${p[2]} ${p[0]}</div>`).join('')}</div><h2 style="margin-top:18px">Recent activity</h2>${history.length?history.map(e=>`<div class="history"><b>${e.type==='redemption'?'♛ '+esc(e.reward):pillarIcon(e.pillar)+' '+esc(e.pillar)}</b><span style="float:right;color:var(--m)">${new Date(e.createdAt).toLocaleString()}</span></div>`).join(''):'<div class="history">No activity recorded yet.</div>'}</div></div>`;$('#backStudents').onclick=()=>{detailId=null;render()}}

function renderSetup(){const c=currentClass(),students=c?classStudents(c.id):[];screen.innerHTML=`<div class="head"><div><h2>Class Setup</h2><p>Manage classes, rosters, instruments, and student avatars.</p></div><button id="setupBackup" class="secondary">Export Backup</button></div><div class="setup-layout"><aside class="setup-sidebar"><div class="card"><h3>Classes</h3><label for="setupClass">Selected class</label><select id="setupClass" class="class-select">${activeClasses().map(x=>`<option value="${esc(x.id)}" ${x.id===c?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="toolbar" style="margin:10px 0 0"><button id="newClass" class="primary">New class</button><button id="renameClass" class="secondary" ${c?'':'disabled'}>Rename</button><button id="archiveClass" class="danger" ${c?'':'disabled'}>Archive</button></div></div><div class="card" style="margin-top:14px"><h3>Bulk roster entry</h3><p>One display name per line. Instrument can be added later.</p><textarea id="bulkNames" class="field" placeholder="Alex R.&#10;Jordan M.&#10;Taylor S."></textarea><button id="previewBulk" class="primary" style="margin-top:9px">Preview students</button><hr style="border:0;border-top:1px solid var(--l);margin:16px 0"><h3>CSV roster</h3><p>Columns: Display Name, Instrument</p><div class="toolbar" style="margin:9px 0 0"><button id="chooseCsv" class="secondary">Choose CSV</button><button id="exampleCsv" class="quiet">Example CSV</button></div></div></aside><section><div class="toolbar"><button id="addStudent" class="primary" ${c?'':'disabled'}>Add Student</button><input id="setupSearch" class="search" style="margin-left:auto" placeholder="Search this roster" value="${esc(query)}"><span class="count">${students.length} students</span></div>${c?rosterTable(students.filter(s=>s.name.toLowerCase().includes(query.toLowerCase()))):'<div class="empty">Create a class to begin.</div>'}</section></div>`;
 $('#setupBackup').onclick=exportBackup;$('#newClass').onclick=()=>classDialog();$('#renameClass').onclick=()=>classDialog(c);$('#archiveClass').onclick=archiveClass;$('#addStudent').onclick=()=>studentDialog(null,c.id);$('#setupClass')?.addEventListener('change',e=>{state.currentClassId=e.target.value;query='';saveState();render()});$('#setupSearch').oninput=e=>{query=e.target.value;render();$('#setupSearch').focus();$('#setupSearch').setSelectionRange(query.length,query.length)};$('#previewBulk').onclick=()=>previewRows($('#bulkNames').value.split(/\r?\n/).map((name,i)=>({name:name.trim(),instrument:'',line:i+1})).filter(r=>r.name),'Bulk roster');$('#chooseCsv').onclick=()=>csvInput.click();$('#exampleCsv').onclick=()=>download('character-cash-roster-example.csv',new Blob(['Display Name,Instrument\nAlex R.,Clarinet\nJordan M.,Trumpet\n'],{type:'text/csv'}));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>studentDialog(studentById(b.dataset.edit),c.id));document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{pendingAvatarId=b.dataset.avatar;avatarInput.value='';avatarInput.click()});document.querySelectorAll('[data-remove-avatar]').forEach(b=>b.onclick=()=>removeAvatar(b.dataset.removeAvatar));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveStudent(b.dataset.move,b.dataset.direction));
}
function rosterTable(students){if(!students.length)return '<div class="empty">No students are in this class yet.</div>';return `<div class="table-wrap"><table class="roster-table"><thead><tr><th>Avatar</th><th>Display name</th><th>Instrument</th><th>Balance</th><th>Actions</th></tr></thead><tbody>${students.map(s=>`<tr><td class="avatar-cell">${avatarMarkup(s,'roster-avatar')}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.instrument||'—')}</td><td>$${s.balance}</td><td><div class="row-actions"><button data-avatar="${esc(s.id)}">Upload / Replace</button><button data-remove-avatar="${esc(s.id)}">Remove avatar</button><button data-edit="${esc(s.id)}">Edit</button><button data-move="${esc(s.id)}" data-direction="up" aria-label="Move up">↑</button><button data-move="${esc(s.id)}" data-direction="down" aria-label="Move down">↓</button></div></td></tr>`).join('')}</tbody></table></div>`}
function showDialog(html){dialogBody.innerHTML=`<div class="dialog-inner">${html}</div>`;dialog.showModal();dialog.querySelector('[data-close]')?.addEventListener('click',()=>dialog.close())}
function classDialog(c=null){showDialog(`<form id="classForm"><h2>${c?'Rename class':'Create a class'}</h2><label class="form-label" for="className">Class name</label><input id="className" class="field" required maxlength="80" value="${esc(c?.name||'')}"><div class="dialog-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save class</button></div></form>`);$('#classForm').onsubmit=e=>{e.preventDefault();const name=$('#className').value.trim();if(!name)return;if(activeClasses().some(x=>x.id!==c?.id&&x.name.toLowerCase()===name.toLowerCase()))return toast('A class with that name already exists.',true);if(c)c.name=name;else{const n={id:uid('class'),name,archived:false};state.classes.push(n);state.currentClassId=n.id}saveState();dialog.close();render();toast(c?'Class renamed.':'Class created.')}}
function archiveClass(){const c=currentClass();if(!c||!confirm(`Archive ${c.name}? Its students, balances, history, and avatars remain in backups.`))return;c.archived=true;state.currentClassId=activeClasses()[0]?.id||null;saveState();render();toast('Class archived.')}
function studentDialog(s,classId){showDialog(`<form id="studentForm"><h2>${s?'Edit student':'Add student'}</h2><label class="form-label" for="studentName">Display name</label><input id="studentName" class="field" required maxlength="80" value="${esc(s?.name||'')}"><label class="form-label" for="studentInstrument">Instrument</label><input id="studentInstrument" class="field" maxlength="80" value="${esc(s?.instrument||'')}"><label class="form-label" for="studentBalance">Starting balance</label><input id="studentBalance" class="field" type="number" min="0" max="9999" value="${s?.balance??0}"><p class="helper">Use the name you want projected on the classroom board.</p><div class="dialog-actions">${s?'<button id="deleteStudent" type="button" class="danger">Delete student</button>':''}<button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save student</button></div></form>`);if(s)$('#deleteStudent').onclick=()=>deleteStudent(s.id);$('#studentForm').onsubmit=e=>{e.preventDefault();const name=$('#studentName').value.trim(),instrument=$('#studentInstrument').value.trim(),balance=Number($('#studentBalance').value);if(!name||!Number.isFinite(balance)||balance<0)return;const dup=state.students.some(x=>x.classId===classId&&x.id!==s?.id&&x.name.toLowerCase()===name.toLowerCase());if(dup)return toast('That display name already exists in this class.',true);if(s){s.name=name;s.instrument=instrument;s.balance=balance}else state.students.push({id:uid('student'),classId,name,instrument,balance,createdAt:now()});saveState();dialog.close();render();toast(s?'Student updated.':'Student added.')}}
async function deleteStudent(id){const s=studentById(id);if(!s||!confirm(`Delete ${s.name}? This removes the student, balance, history, and avatar.`))return;state.students=state.students.filter(x=>x.id!==id);state.events=state.events.map(e=>({...e,studentIds:e.studentIds.filter(x=>x!==id)})).filter(e=>e.studentIds.length);try{await avatarDelete(id)}catch(e){}saveState();dialog.close();render();toast('Student deleted.')}
function moveStudent(id,direction){const same=classStudents(),from=same.findIndex(s=>s.id===id),to=direction==='up'?from-1:from+1;if(from<0||to<0||to>=same.length)return;const a=state.students.findIndex(s=>s.id===same[from].id),b=state.students.findIndex(s=>s.id===same[to].id);[state.students[a],state.students[b]]=[state.students[b],state.students[a]];saveState();render()}
function parseCsvLine(line){const out=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){out.push(value.trim());value=''}else value+=ch}out.push(value.trim());return out}
csvInput.onchange=async()=>{const file=csvInput.files[0];if(!file)return;if(file.size>1024*1024)return toast('CSV is too large. Use a file under 1 MB.',true);try{const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),start=/display\s*name/i.test(lines[0]||'')?1:0,rows=lines.slice(start).map((line,i)=>{const cells=parseCsvLine(line);return {name:(cells[0]||'').trim(),instrument:(cells[1]||'').trim(),line:i+start+1}});previewRows(rows,'CSV roster')}catch(e){toast('The CSV could not be read.',true)}};
function previewRows(rows,label){const c=currentClass();if(!c)return toast('Create or select a class first.',true);const existing=new Set(classStudents(c.id).map(s=>s.name.toLowerCase())),seen=new Set(),valid=[],issues=[];rows.forEach(r=>{if(!r.name)issues.push(`Line ${r.line}: missing display name`);else if(r.name.length>80)issues.push(`Line ${r.line}: name is too long`);else if(existing.has(r.name.toLowerCase()))issues.push(`Line ${r.line}: ${r.name} already exists`);else if(seen.has(r.name.toLowerCase()))issues.push(`Line ${r.line}: duplicate ${r.name}`);else{seen.add(r.name.toLowerCase());valid.push(r)}});showDialog(`<h2>${esc(label)} preview</h2><p>${valid.length} ready for <b>${esc(c.name)}</b>. ${issues.length} need attention.</p><div class="preview-list">${valid.map(r=>`<div><b>${esc(r.name)}</b>${r.instrument?' — '+esc(r.instrument):''}</div>`).join('')}${issues.map(i=>`<div class="bad">${esc(i)}</div>`).join('')}</div><div class="dialog-actions"><button class="secondary" data-close>Cancel</button><button id="confirmImport" class="primary" ${valid.length?'':'disabled'}>Add ${valid.length} students</button></div>`);$('#confirmImport').onclick=()=>{valid.forEach(r=>state.students.push({id:uid('student'),classId:c.id,name:r.name,instrument:r.instrument,balance:0,createdAt:now()}));saveState();dialog.close();render();toast(`${valid.length} students added.`)}}
avatarInput.onchange=async()=>{const file=avatarInput.files[0],s=studentById(pendingAvatarId);if(!file||!s)return;if(!['image/png','image/jpeg'].includes(file.type))return toast('Choose a PNG or JPEG image.',true);if(file.size>MAX_IMAGE_BYTES)return toast('That image is over 5 MB.',true);try{const blob=await resizeImage(file),previewUrl=URL.createObjectURL(blob);showDialog(`<h2>Save avatar for ${esc(s.name)}?</h2><p>The full image was resized to a compact square.</p><img id="avatarPreview" class="avatar" style="width:180px;height:180px;display:block;margin:12px auto"><div class="dialog-actions"><button class="secondary" data-close>Cancel</button><button id="saveAvatar" class="primary">Save avatar</button></div>`);$('#avatarPreview').src=previewUrl;$('#saveAvatar').onclick=async()=>{try{await avatarPut(s.id,blob);URL.revokeObjectURL(previewUrl);dialog.close();render();toast(`Avatar saved for ${s.name}.`)}catch(e){toast('The avatar could not be saved. Check browser storage.',true)}}}catch(e){toast('The image could not be decoded.',true)}};
function resizeImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const size=256,c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle='#eef1f5';x.fillRect(0,0,size,size);x.imageSmoothingEnabled=false;const scale=Math.min(size/img.width,size/img.height),w=Math.round(img.width*scale),h=Math.round(img.height*scale);x.drawImage(img,Math.floor((size-w)/2),Math.floor((size-h)/2),w,h);c.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error())},'image/png')}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error())};img.src=url})}
async function removeAvatar(id){const s=studentById(id);if(!s||!confirm(`Remove the avatar for ${s.name}?`))return;try{await avatarDelete(id);render();toast('Avatar removed.')}catch(e){toast('The avatar could not be removed.',true)}}
async function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
async function buildBackup(){const avatars={};for(const [id,blob] of await avatarAll())avatars[id]=await blobToDataUrl(blob);return {format:'derby-character-cash-backup',version:BACKUP_VERSION,exportedAt:now(),data:state,avatars}}
async function exportBackup(){try{const backup=await buildBackup(),date=new Date().toISOString().slice(0,10);download(`derby-character-cash-backup-${date}.json`,new Blob([JSON.stringify(backup)],{type:'application/json'}));toast('Backup downloaded. Keep it in a school-approved location.')}catch(e){toast('The backup could not be created.',true)}}
function validateBackup(b){if(!b||b.format!=='derby-character-cash-backup'||b.version!==BACKUP_VERSION||!validateState(b.data)||!b.avatars||typeof b.avatars!=='object')return false;const ids=new Set(b.data.students.map(s=>s.id));return Object.entries(b.avatars).every(([id,url])=>ids.has(id)&&typeof url==='string'&&url.startsWith('data:image/'))}
restoreInput.onchange=async()=>{const file=restoreInput.files[0];if(!file)return;try{if(file.size>30*1024*1024)throw new Error();const backup=JSON.parse(await file.text());if(!validateBackup(backup))return toast('Invalid backup. Current data was not changed.',true);showDialog(`<h2>Restore backup?</h2><p>This contains <b>${backup.data.classes.length} classes</b>, <b>${backup.data.students.length} students</b>, and <b>${Object.keys(backup.avatars).length} avatars</b>.</p><p>Restoring replaces the classroom data saved in this browser.</p><div class="dialog-actions"><button id="backupFirst" class="secondary">Export current first</button><button class="secondary" data-close>Cancel</button><button id="confirmRestore" class="danger">Replace and restore</button></div>`);$('#backupFirst').onclick=exportBackup;$('#confirmRestore').onclick=()=>restoreBackup(backup)}catch(e){toast('The backup could not be read. Current data was not changed.',true)}};
async function restoreBackup(backup){try{const entries=[];for(const [id,url] of Object.entries(backup.avatars)){const blob=await(await fetch(url)).blob();if(!['image/png','image/jpeg'].includes(blob.type))throw new Error();entries.push([id,blob])}const previous=state,previousAvatars=await avatarAll();await avatarReplaceAll(entries);state=backup.data;if(!saveState()){state=previous;await avatarReplaceAll(previousAvatars);throw new Error()}dialog.close();view='class';render();toast('Backup restored.')}catch(e){toast('Restore failed. Current data was not changed.',true)}}
function renderSettings(){const c=currentClass();screen.innerHTML=`<div class="head"><div><h2>Settings</h2><p>Display preferences and local data tools.</p></div></div><div class="settings"><div class="card"><h3>Class on return</h3><p>Choose the class shown when the classroom screen opens.</p><select id="defaultClass" class="class-select" style="margin-top:13px">${activeClasses().map(x=>`<option value="${esc(x.id)}" ${x.id===c?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="card"><button id="animationToggle" role="switch" aria-label="Recognition animation" aria-checked="${state.settings.animation}" class="toggle ${state.settings.animation?'on':''}"></button><h3>Recognition animation</h3><p>Show the brief balance animation after an award.</p></div><div class="card"><h3>Export backup</h3><p>Download classes, students, balances, activity, settings, and avatars.</p><button id="exportBackup" class="primary" style="margin-top:13px">Export Backup</button></div><div class="card"><h3>Restore backup</h3><p>Validate and restore a previous backup. A summary appears before replacement.</p><button id="restoreBackup" class="secondary" style="margin-top:13px">Choose Backup</button></div></div><div class="note"><b>LOCAL DEVICE STORAGE</b><br>Your classroom data is saved in this browser on this device. It does not automatically sync to another device. Clearing browser data may remove it. Export a backup regularly and keep it in a school-approved location, never in the public GitHub repository.</div>`;$('#defaultClass')?.addEventListener('change',e=>{state.currentClassId=e.target.value;saveState();toast('Default class updated.')});$('#animationToggle').onclick=()=>{state.settings.animation=!state.settings.animation;saveState();render()};$('#exportBackup').onclick=exportBackup;$('#restoreBackup').onclick=()=>{restoreInput.value='';restoreInput.click()}}
render();
})();
